### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by bms3-33** [jimmy54/iRime#2]
你好，我同步的LibAndResource，把文件夹放入到了iRime里面，编译出现下面的错误
![image](https://cloud.githubusercontent.com/assets/12210918/21769421/95222758-d6b9-11e6-884e-d6eb7b38cbaf.png)

**Comment by jimmy54** [comment]
感觉你工程不够完整，LibAndResource总共5百多M。你看一看是不是少了。

**Comment by bms3-33** [comment]
LibAndResource一共有570.2 MB，已经同步完成了

**Comment by hlouis** [comment]
同样的问题，最后链接错误

<img width="241" alt="irime_link_err" src="https://cloud.githubusercontent.com/assets/79014/21800096/037322b4-d757-11e6-8833-4827cb8a4f78.png">

系统：macOS 10.12.2
Xcode 8.2.1

**Comment by jimmy54** [comment]
你们应该用的是模拟器环境。目前不支持模拟器环境。用真机环境没有问题。

**Comment by bms3-33** [comment]
更新Xcode后，连上手机后 processing symbol files 结束后，错误清除

**Comment by pofat** [comment]
同样的问题，最后链接错误，沒有种子無法同步， 故用下載後再拖入 project navigator， 最後仍然報錯
![image](https://user-images.githubusercontent.com/4652318/34113268-25456478-e44a-11e7-8396-317d4b9cf5e5.png)

macOS 10.13.2
Xcode 9.2
真机环境(arm64)

請問該如何是好？
