### ISSUE TITLE
ios xcode rime 编译

### ISSUE THREAD

**Issue by cntys** [jimmy54/iRime#25]
您好，我通过xcode编译了一个能在iOS设备上能用的rime的.a库，但是在项目使用librime.a的时候一直报
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > boost::locale::conv::to_utf<char>(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::locale::conv::method_type)", referenced from:
      rime::CodepointTranslator::Query(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rime::Segment const&) in liblibrime.a(codepoint_translator.o)
      std::__1::__function::__func<rime::CodepointTranslator::Initialize()::$_2, std::__1::allocator<rime::CodepointTranslator::Initialize()::$_2>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblibrime.a(codepoint_translator.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > boost::locale::conv::from_utf<char>(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::locale::conv::method_type)", referenced from:
      rime::CharsetFilter::FilterText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblibrime.a(charset_filter.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
我已经在项目中添加了libc++这个库了，请问您是怎么编译？

**Comment by pofat** [comment]
請問能分享下您憅麼編譯的嗎？

**Comment by 1016990109** [comment]
> 您好，我通过xcode编译了一个能在iOS设备上能用的rime的.a库，但是在项目使用librime.a的时候一直报
> "std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > boost::locale::conv::to_utf(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, boost::locale::conv::method_type)", referenced from:
> rime::CodepointTranslator::Query(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, rime::Segment const&) in liblibrime.a(codepoint_translator.o)
> std::__1::__function::__func<rime::CodepointTranslator::Initialize()::$_2, std::__1::allocatorrime::CodepointTranslator::Initialize()::$_2, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > (std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in liblibrime.a(codepoint_translator.o)
> "std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > boost::locale::conv::from_utf(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, boost::locale::conv::method_type)", referenced from:
> rime::CharsetFilter::FilterText(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in liblibrime.a(charset_filter.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 我已经在项目中添加了libc++这个库了，请问您是怎么编译？

@cntys 请问您是如果解决这个问题的呢？
