### ISSUE TITLE
版本 1.4.2 在选字方面有严重问题

### ISSUE THREAD

**Issue by Kahaani** [jimmy54/iRime#28]
7月10日发布的 1.4.2 版在选字造词方面有严重的 regression，导致这个功能几乎不能用。

以全拼为例。打一个词库中没有的词，比如「微信」。键入「weixin」，先选择第一个字「微」。

![wechatimg1](https://user-images.githubusercontent.com/3883845/28171382-d2c54b06-681a-11e7-943e-350aad0d2ef8.jpeg)

候选栏显示「微xin」，这时候想选择第二个字。但候选项仍然显示「weixin」和「wei」的匹配项而不是「xin」。

![wechatimg2](https://user-images.githubusercontent.com/3883845/28171393-db06137c-681a-11e7-9a58-638a8e119081.jpeg)

往下翻几页，终于找到「信」字，点击该字，并不能成功选到候选栏中。

![wechatimg3](https://user-images.githubusercontent.com/3883845/28171397-dd6d1818-681a-11e7-8ea2-1c3158af480f.jpeg)

**Comment by jimmy54** [comment]
fix

**Comment by jimmy54** [comment]
fix in 1.4.4

**Comment by Kahaani** [comment]
fixed in 1.4.3
