### ISSUE TITLE
为什么pull下来的工程缺一大堆文件（如LibAndResource文件），请问上哪找去？

### ISSUE THREAD

**Issue by iCodist** [jimmy54/iRime#37]

**Comment by xqin** [comment]
下载地址(百度盘):
链接: http://pan.baidu.com/s/1mi0wt88 密码: ey9v

**Comment by goddade** [comment]
> 下载地址(百度盘): 链接: http://pan.baidu.com/s/1mi0wt88 密码: ey9v

链接失效了能麻烦补一个么？
