### ISSUE TITLE
双拼输入法输入英文的问题

### ISSUE THREAD

**Issue by janmelin** [jimmy54/iRime#40]
双拼输入法return上屏的不是commit_code而是commit_text。这使得我在中文状态下输入英文时发现打出来的是拼音而非我按的键。
请问有什么办法能直接在中文状态下顺畅地完成英文输入？

**Comment by chowhoyin** [comment]
有圖嗎？不是很確定「打出来的是拼音而非我按的键」是怎樣個效果

**Comment by janmelin** [comment]
举个例子，我用的是自然码，按下p+h时输入法会识别成p+ang，此时按下return上屏的就是pang。如果我只想输入英文ph就必须切换的英文状态下。

**Comment by chowhoyin** [comment]
上屏碼（即候選字欄上面那一小欄所顯示的內容）對應的配置項是方案文件裏 translator 的 preedit_format，你需要在這裏作修改
