### ISSUE TITLE
iPad 外接 magic keyboard 出现问题

### ISSUE THREAD

**Issue by angela0** [jimmy54/iRime#50]
设备：iPad Pro
系统：11.2.6
输入法版本：当前版本 2.0；小版本 1
问题描述：外接 magic keyboard 输入时，调用的是系统的默认中文输入法，而不是 iRime

**Comment by hlouis** [comment]
这是 iOS 系统限制的问题，外接键盘是无法使用任何第三方输入法的。

**Comment by angela0** [comment]
明白了，谢谢
