### ISSUE TITLE
五笔98方案在更新 v2.2 后无法出字

### ISSUE THREAD

**Issue by pihao** [jimmy54/iRime#51]
OS: iOS 12
Ver: 2.2

刚更新到 iOS 12, 更新之前一切正常, 更新后五笔98方案无法出字. 即候选那里不出字. 输入标点正常, 其它方案也正常.

**Comment by chowhoyin** [comment]
還原一下吧

**Comment by pihao** [comment]
配置重置了, 还是不行.

另外: iOS12 系统是通过恢复来升级的, 也就是完全重装了, iRime也是重新下载的

**Comment by chowhoyin** [comment]
把iRime裏五筆98的schema，dict，bin刪掉，重新上傳過schema和dict試試。還是不行的話就進群報下bug吧

**Comment by pihao** [comment]
原来问题出在自定义配置. 再次重装 iRime 时, 没有上传 wubi98 的 custom 配置, 就恢复正常了. 
经过多次尝试, 发现自定义的 ascii_mode 默认设置为英文时, 会导致这个问题.

那么 bug 来了: 设置为英文时应该自动切换到 iRime 的英文模式.

@chowhoyin telegram吗? 群号多少?

**Comment by chowhoyin** [comment]
Q群：234535778。大概作者的思路是，要打英文就用iRime專門的英文鍵盤吧…

**Comment by kahaani** [comment]
你好。我似乎遇到同样问题了，试过上述讨论的方法不奏效。请问可以帮忙看看是什么问题吗？谢谢。

版本：2.3.2

步骤：重置iRime。上传`X.schema.yaml`和`X.dict.yaml`。在`default.custom.yaml`中添加新方案X。重新deploy。

`X.schema.yaml`中关于`ascii_mode`的配置是：

```yaml
- name: ascii_mode
  reset: 0
  states: [ 中文, 西文 ]
```

现象：没有候选字，但是标点符号可以正常输入。

![wechatimg9](https://user-images.githubusercontent.com/3883845/52632648-0eb72d00-2efd-11e9-9004-08b2dea7c721.jpeg)

**Comment by kahaani** [comment]
```
entry_collector.cc:145 Encode failure: 'Â∂µ'.
```

log中有大量这样的错误，应该是deploy过程中产生的。

**Comment by pihao** [comment]
整个是新方案吗？这不好定位问题。建议在已有方案上一步步改，看是哪步出了问题。

**Comment by kahaani** [comment]
@pihao 谢谢回复。是老方案，在小狼毫/鼠须管、老版本iRime上都可以用。
https://github.com/Kahaani/dieghv/blob/master/dieziu.schema.yaml

请问我上述几个步骤和你配置成功的方法是一样的吗？

**Comment by pihao** [comment]
步骤没问题，看起来是配置哪里不对导致的。另外，上传配置前要先删除旧配置。

**Comment by laubonghaudoi** [comment]
@pihao 我刚刚在别的方案上也尝试部署了一下，发现的确出现此问题，而这些方案在2.3版本的时候都是能正常使用的。我也有删除旧的配置，所有步骤均严格按照这个[教程页面](https://laubonghaudoi.github.io/dialects/install/ios.html)来，所以应该不是方案配置的问题，是在2.3.2更新后引入的bug，希望能尽快修复。

**Comment by kahaani** [comment]
@jimmy54 @chowhoyin 你们好。报一个bug，上述应该是一个regression，版本2.3.2部署失败。而原来自己编译的prism.bin/reverse.bin/table.bin也不起作用。
