### ISSUE TITLE
同音字只能顯示26個

### ISSUE THREAD

**Issue by uliloewi** [jimmy54/iRime#57]
把dict.yaml和schema.yaml傳到手機，用irime編譯後，拼音輸入只能顯示26個同音字以供選擇。但有時碼表中的同音字遠超26個。
我是用https://github.com/uliloewi/lang2jin1 中的碼表測試的。

**Comment by ctermiii** [comment]
同样问题，怎么增加候选字字数呢？

**Comment by uliloewi** [comment]
> 同样问题，怎么增加候选字字数呢？

旁邊有下拉箭頭。點一下出現所有字。

**Comment by ctermiii** [comment]
下拉里面也不够多

**Comment by ctermiii** [comment]
> > 同样问题，怎么增加候选字字数呢？
> 
> 旁邊有下拉箭頭。點一下出現所有字。

你有成功吗？
